import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "./[locale]/globals.css";
import "./[locale]/fontawesome";

import Header from "@/components/header";
import Footer from "@/components/footer";

const Vietnam = Be_Vietnam_Pro({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Vietnam.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
