import type { Metadata } from "next";
import { Be_Vietnam_Pro, Cairo } from "next/font/google";
import "./globals.css";
import "./fontawesome";

import Header from "@/components/header";
import Footer from "@/components/footer";
import { Locale } from "@/i8n.config";
import { Directions, Languages } from "@/constants/enums";
import PageTransition from "@/components/PageTransition";
import LoadingWrapper from "@/components/LoadingWrapper";

const Vietnam = Be_Vietnam_Pro({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const cairo = Cairo({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: Locale }>;
}>) {
  const locale = (await params).locale;
  const fontClass =
    locale === Languages.ARABIC ? cairo.className : Vietnam.className;

  return (
    <html
      lang={locale}
      dir={locale === Languages.ARABIC ? Directions.RTL : Directions.LTR}
    >
      <body className={fontClass}>
        <Header />
        <LoadingWrapper>
          <PageTransition>{children}</PageTransition>
        </LoadingWrapper>
        <Footer />
      </body>
    </html>
  );
}
